version: '3.8'

services:
  hacker-shop:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    container_name: hacker-goods-mall
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - hacker-shop
  #   restart: unless-stopped
